### PR TITLE
Add ldmsd_stream_dir_test

### PR DESCRIPTION
**Pull request by nichamon**
The script tests the correctness of the stream_dir and prdcr_stream_dir
responses in various situation

### CODE REVIEW

**Comment by nichamon** [comment]
@tom95858 Here is the test script for the STREAM_DIR and PRDCR_STREAM_DIR config messages

**Comment by tom95858** [comment]
@nichamon, Do we have similar tests in TADA; where they can be run as a regression test?

**Comment by tom95858** [comment]
Also, these tests seem to be in ovis-hpc/master. This doesn't seem correct...

**Comment by nichamon** [comment]
@tom95858 This is the TADA repo. The master branch is the only branch in the ldms-test repo. I have modified the patch to add the new test to the weekly regression test run on cygnus.

**Pull request merged**
