### PR TITLE
Support test scripts that runs inside containers

### PR DESCRIPTION
**Pull request by nichamon**

### CODE REVIEW

**Comment by nichamon** [comment]
@narategithub Here is the code

**Comment by tom95858** [comment]
Are these pull requests still drafts?

**Comment by nichamon** [comment]
> Are these pull requests still drafts?

Yes, I'm using it to develop the test cases for the prdcr_# config commands. I have been bug fixing and improving it to suit the actual test development. I'll mark it as ready when my local branch is stable.

**Comment by nichamon** [comment]
@narategithub How should I incorporate ```run_inside_cont_test``` script? The script runs all test scripts to run executed in a container.

**Comment by narategithub** [comment]
I think just add `run_inside_conf_test.py` into the `CONT_TEST_LIST` in `test-list.sh`.

Just to be clear, `run_inside_conf_test.py` will always run all tests discovered in `inside_cont_tests/`, right?

**Comment by nichamon** [comment]
> I think just add `run_inside_conf_test.py` into the `CONT_TEST_LIST` in `test-list.sh`.

Done.

> Just to be clear, `run_inside_conf_test.py` will always run all tests discovered in `inside_cont_tests/`, right?

Yes! To be precise, `run_inside_cont_test.py` runs all python scripts that contain a single class inheriting from ContainerTest in LDMS_Test.py.

**Pull request merged**
