### PR TITLE
Add the test coverage for libovis_log

### PR DESCRIPTION
**Pull request by nichamon**

### CODE REVIEW

**Comment by nichamon** [comment]
The patch is to accompany the ovis_log library in https://github.com/ovis-hpc/ovis/pull/1107.

**Comment by nichamon** [comment]
@narategithub @tom95858 The pull request is ready to be merged.

**Comment by tom95858** [comment]
Hi @nichamon, if you still want this pull request, could you please rebase? The same for the one #35.

**Comment by nichamon** [comment]
@tom95858 I changed this to a draft because I want to update this to be compatible with your changes in the ovis_log library.

**Comment by nichamon** [comment]
@tom95858 I updated the test script to use the new `ldmsd_log_register()` name. It is ready.

**Pull request merged**
