### PR TITLE
Add the test coverage for long config lines

### PR DESCRIPTION
**Pull request by nichamon**

### CODE REVIEW

**Comment by nichamon** [comment]
I ported this from [ldms/python/test/ldmsd/ldmsd_long_config.py](https://github.com/ovis-hpc/ovis/blob/OVIS-4/ldms/python/test/ldmsd/ldmsd_long_config.py).

**Comment by tom95858** [comment]
@nichamon should I take this? I'm guessing yes?

**Comment by nichamon** [comment]
Yes, please.

**Comment by tom95858** [comment]
@nichamon sorry it has merge conflicts and needs to be rebased. Can you do that for me?

**Comment by nichamon** [comment]
I just rebased the patch. :)

**Pull request merged**
